version: '3.7'

services:
  jupyterlab:
    build: .docker
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-docker}
    ports:
      - "8888:8888"
    volumes:
      - ./data:/opt/app/data
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'
